from Seq1 import Seq
print("-----| Practice 1 Exercise 6 |------")
seq = Seq("TATAC")
seq2 = Seq()
seq3 =Seq("Invalid")
print(f"Sequence 1: {seq} (Length: {seq.length()}) ")
print(f"Bases:, {seq.count()}")
print()
print(f"Sequence 1: {seq2} (Length: {seq2.length()}) ")
print(f"Bases:, {seq2.count()}")
print()
print(f"Sequence 1: {seq3} (Length: {seq3.length()}) ")
print(f"Bases:, {seq3.count()}")
print()